# Generated by Django 4.1.2 on 2022-10-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleListApp', '0002_alter_person_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
    ]
