# Generated by Django 4.1.2 on 2022-10-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peopleListApp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
